const SET_START_VALUE = "SET_START_VALUE";
const SET_MAX_VALUE = "SET_MAX_VALUE";
const SET_DISPLAY_VALUE = "SET_DISPLAY_VALUE";
const SET_ERROR = "SET_ERROR";
const LOAD_STORAGE_VALUE = "LOAD_STORAGE_VALUE";

export enum COUNTER_TYPES {
    SET_START_VALUE,
    SET_MAX_VALUE,
    SET_DISPLAY_VALUE,
    SET_ERROR,
    LOAD_STORAGE_VALUE,
}

